import type { MealNeed } from "./types";

function isoDaysFromNow(days: number): string {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

/** Demo-only Chicago-style placeholders — not real vetted orgs. */
export function buildSeedNeeds(): MealNeed[] {
  const now = new Date().toISOString();
  return [
    {
      id: "need-demo-01",
      title: "Christmas-style dinner for elders",
      charityName: "Northside Elder Circle (demo)",
      neighborhood: "Rogers Park",
      date: isoDaysFromNow(12),
      mealType: "dinner",
      headcount: 20,
      dietRules: "No pork; soft options welcome",
      allergens: "List nuts if used; dairy OK",
      deliveryWindow: "4:00–5:30 PM",
      notes: "Warm trays preferred. Demo listing for pilot UI.",
      status: "open",
      createdAt: now,
    },
    {
      id: "need-demo-02",
      title: "Saturday shelter breakfasts",
      charityName: "River Bend Day Center (demo)",
      neighborhood: "Pilsen",
      date: isoDaysFromNow(5),
      mealType: "breakfast",
      headcount: 250,
      dietRules: "Halal-friendly preferred; vegetarian tray required",
      allergens: "No peanut butter in bulk trays",
      deliveryWindow: "6:30–8:00 AM",
      status: "open",
      createdAt: now,
    },
    {
      id: "need-demo-03",
      title: "Weeknight soup & bread",
      charityName: "Lantern House Welcome Table (demo)",
      neighborhood: "Uptown",
      date: isoDaysFromNow(3),
      mealType: "dinner",
      headcount: 40,
      dietRules: "Vegetarian base + optional chicken",
      allergens: "Gluten in bread — label clearly",
      deliveryWindow: "5:00–6:00 PM",
      status: "open",
      createdAt: now,
    },
    {
      id: "need-demo-04",
      title: "Youth lock-in pizza night",
      charityName: "Midway Youth Mentors (demo)",
      neighborhood: "Brighton Park",
      date: isoDaysFromNow(8),
      mealType: "dinner",
      headcount: 35,
      dietRules: "2 cheese + 2 veggie pizzas minimum",
      allergens: "Note dairy; offer one dairy-free pie if able",
      deliveryWindow: "6:00–7:00 PM",
      status: "open",
      createdAt: now,
    },
    {
      id: "need-demo-05",
      title: "Lunch boxes for job-training cohort",
      charityName: "Work Ready Kitchen Lab (demo)",
      neighborhood: "Austin",
      date: isoDaysFromNow(2),
      mealType: "lunch",
      headcount: 28,
      dietRules: "Balanced plates; one vegetarian option",
      allergens: "None known — label ingredients",
      deliveryWindow: "11:30 AM–12:30 PM",
      status: "open",
      createdAt: now,
    },
    {
      id: "need-demo-06",
      title: "Sunday brunch for family shelter",
      charityName: "Oak & Maple Family Lodge (demo)",
      neighborhood: "Garfield Park",
      date: isoDaysFromNow(14),
      mealType: "breakfast",
      headcount: 60,
      dietRules: "Kid-friendly; fruit on the side",
      allergens: "Avoid tree nuts",
      deliveryWindow: "10:00–11:30 AM",
      status: "open",
      createdAt: now,
    },
    {
      id: "need-demo-07",
      title: "Warm dinner after ESL class",
      charityName: "Open Mind Language Hall (demo)",
      neighborhood: "Albany Park",
      date: isoDaysFromNow(6),
      mealType: "dinner",
      headcount: 45,
      dietRules: "Halal; mild spice",
      allergens: "Sesame common — label",
      deliveryWindow: "7:00–8:00 PM",
      status: "open",
      createdAt: now,
    },
    {
      id: "need-demo-08",
      title: "Snack packs for after-school",
      charityName: "South Loop Scout Hall (demo)",
      neighborhood: "Bronzeville",
      date: isoDaysFromNow(4),
      mealType: "snack",
      headcount: 50,
      dietRules: "Individually wrapped preferred",
      allergens: "Nut-free pack required",
      deliveryWindow: "3:00–4:00 PM",
      status: "open",
      createdAt: now,
    },
    {
      id: "need-demo-09",
      title: "Friday fish fry tray (demo)",
      charityName: "Harbor Light Men's Home (demo)",
      neighborhood: "Back of the Yards",
      date: isoDaysFromNow(9),
      mealType: "dinner",
      headcount: 55,
      dietRules: "No pork sides",
      allergens: "Fish; offer a non-fish tray too",
      deliveryWindow: "5:30–6:30 PM",
      status: "open",
      createdAt: now,
    },
    {
      id: "need-demo-10",
      title: "Holiday cookie & cocoa cart",
      charityName: "Quiet Grid Winter Warmth (demo)",
      neighborhood: "Logan Square",
      date: isoDaysFromNow(18),
      mealType: "snack",
      headcount: 80,
      dietRules: "Include gluten-free cookies if possible",
      allergens: "Label wheat, dairy, eggs",
      deliveryWindow: "2:00–4:00 PM",
      status: "open",
      createdAt: now,
    },
  ];
}
